version: "3"
services:
  # 其他配置参考 https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi/
  # 与go-cqhttp同时部署
  gocqhttp:
    image: pcrbot/gocqhttp:ffmpeg
    volumes:
      - ./gocqhttp:/data:delegated # 用于保存 gocqhttp 相关文件，请复制 config.yml 等文件到此
    tty: true
    stdin_open: true
    environment:
      - TZ=Asia/Shanghai
    network_mode: host
    depends_on:
      - nonebot
  nonebot:
    image: inscripoem/xunlibot:latest
    container_name: nonebot
    volumes:
      - ./env:/app/env
    environment:
      - ENVIRONMENT=prod # 配置 nonebot 运行环境，此项会被 .env 文件覆盖
      - APP_MODULE=bot:app # 配置 asgi 入口
      - MAX_WORKERS=1 # 如果你有多个QQ，且存在 self_id 指定，多个 worker 会导致无法找到其他 websocket 连接
      - TZ=Asia/Shanghai
    network_mode: host